### PR TITLE
Abhishek_Srivastava.cpp

### PR DESCRIPTION
**Pull request by AbhishekSrivastava-23**
Solved the anagrams problem using in-built sort function of O(NlogN) time complexity.
Please accept my solution and mark it as Hacktoberfest accepted.

### CODE REVIEW

**Review by onkardighe — CHANGES_REQUESTED** [review]
change fileName  -> 

`firstName_lastName.(Extension)`

**Comment by AbhishekSrivastava-23** [comment]
Sir, I have changed the file name.
Is it now correct?

**Comment by onkardighe** [comment]
Great !

**Review by onkardighe — APPROVED** [review]

**Comment by AbhishekSrivastava-23** [comment]
Thank you sir
Can you please add Hacktoberfest accepted tag to it

**Pull request merged**
