### PR TITLE
Create AG.cpp

### PR DESCRIPTION
**Pull request by aditi-gulati**

### CODE REVIEW

**Comment by aditi-gulati** [comment]
okay @onkardighe please remove invalid tag

**Comment by aditi-gulati** [comment]
@onkardighe please check

**Comment by Yashkapure06** [comment]
> @onkardighe please check

@aditi-gulati Please Raise PR from main Branch and delete patch-1 Branch

**Comment by aditi-gulati** [comment]
Please remove Invalid tag

**Comment by Yashkapure06** [comment]
> Please remove Invalid tag

Raise a PR from **MAIN** Branch

**Pull request closed without merging**
