### PR TITLE
convert uppercase letters to lower case and vice versa in string created by HARSHSUHANE

### PR DESCRIPTION
**Pull request by HARSHSUHANE17**

### CODE REVIEW

**Comment by HARSHSUHANE17** [comment]
@Yashkapure06 is it correct now?

**Comment by HARSHSUHANE17** [comment]
@Yashkapure06 is this correct now?

**Comment by Yashkapure06** [comment]
> @Yashkapure06 is this correct now?

Check Your code for uppercase count. Its not wrong.

**Comment by HARSHSUHANE17** [comment]
@Yashkapure06 please check now. I hope this time it is corrected. Tell me if not corrected.
Thanks

**Comment by HARSHSUHANE17** [comment]
@Yashkapure06 i have corrected the code of 2nd october . Please check .
Thanks.

**Review by onkardighe — APPROVED** [review]

**Pull request merged**
